//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventApplication.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionEvent
    {
        public int EventId { get; set; }
        public string EventTitle { get; set; }
        public string EventDescription { get; set; }
        public System.DateTime EventDate { get; set; }
        public Nullable<System.TimeSpan> EventTime { get; set; }
    }
}
